---
language: node_js

node_js:
  - "6"

sudo: false

cache:
  yarn: true

env:
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-beta
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt
  - phantomjs --version

install:
  - yarn install --no-lockfile

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

after_success:
  - rm -rf travis-phantomjs
  - git remote add deploy https://$GH_TOKEN:x-oauth-basic@github.com/mike-north/ember-load.git
  2>&1 >/dev/null
  - git fetch deploy
  - git branch gh-pages deploy/gh-pages
  - git config user.name "Mike North"
  - git config user.email "michael.l.north@gmail.com"
  - "/bin/bash lib/try-generate-pages.sh"
  - git checkout master
